// Bilingual (German first, English second) membership certificate ("Mitgliedsbescheinigung").
//
// Two variants of the same document:
// - digital: sent by e-mail; states that it was generated by machine and is valid without a
//   signature, and carries a verification code that can be checked on /pruefen.
// - print:   for signing by hand; the signatory's name and position are left blank on purpose
//            (no stamp field).
import { createHmac, timingSafeEqual } from "node:crypto";
import {
  PDFDocument,
  rgb,
  type PDFFont,
  type PDFPage,
  type RGB,
} from "pdf-lib";
import fontkit from "@pdf-lib/fontkit";
import { pdfFont, pdfFontBold } from "./font";
import type { TextSettings } from "./form-settings";
import { monthYear } from "./i18n";
import { PdfGlyphError } from "./pdf";

export const CERT_TEXT_KEYS = [
  "clubName",
  "contactEmail",
  "certSubtitle",
  "certAddress",
  "certPlace",
] as const;
export type CertTexts = Pick<TextSettings, (typeof CERT_TEXT_KEYS)[number]>;
export type CertVariant = "digital" | "print";

export type CertMember = {
  id: string;
  kind: "new" | "existing";
  status: string;
  first_name: string;
  last_name: string;
  /** YYYY-MM-DD */
  birth_date: string;
  decided_at: string | Date | null;
  /** YYYY-MM, existing members only. */
  membership_start_month?: string | null;
};

/** Only accepted members (new) or reviewed existing members get a certificate. */
export function certificateAvailable(row: Pick<CertMember, "kind" | "status">) {
  return (
    (row.kind === "new" && row.status === "approved") ||
    (row.kind === "existing" && row.status === "reviewed")
  );
}

// ---------------------------------------------------------------------------------------------
// Dates

/** Calendar day in Berlin as YYYY-MM-DD. */
export function berlinDay(date: Date | string = new Date()) {
  return new Intl.DateTimeFormat("en-CA", {
    timeZone: "Europe/Berlin",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).format(new Date(date));
}

const longDate = (day: string, locale: "de" | "en") =>
  new Intl.DateTimeFormat(locale === "en" ? "en-GB" : "de-DE", {
    timeZone: "UTC",
    day: "numeric",
    month: "long",
    year: "numeric",
  }).format(new Date(day + "T00:00:00Z"));

const shortDate = (day: string) => day.split("-").reverse().join(".");

/** "seit September 2026" / "since September 2026" – or the admission day for new members. */
export function memberSince(row: CertMember, locale: "de" | "en") {
  if (row.kind === "existing")
    return row.membership_start_month
      ? monthYear(row.membership_start_month, locale)
      : "";
  return row.decided_at ? longDate(berlinDay(row.decided_at), locale) : "";
}

// ---------------------------------------------------------------------------------------------
// Verification code: <first 8 hex of the reference number>-<YYMMDD issue date>-<8 char HMAC>.
// Stateless: nothing is stored, and a deleted or rejected entry no longer verifies.

const B32 = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"; // no I, O, 0, 1

function certSecret() {
  const s = process.env.SESSION_SECRET;
  if (!s || s.length < 32) throw new Error("Session configuration missing");
  return createHmac("sha256", s).update("membership-certificate:v1").digest();
}

function signature(id: string, day: string) {
  const mac = createHmac("sha256", certSecret())
    .update(`${id.toLowerCase()}|${day}`)
    .digest();
  let out = "";
  for (let i = 0; i < 8; i++) out += B32[mac[i] % 32];
  return out;
}

export function certificateCode(id: string, day: string) {
  return `${id.slice(0, 8).toUpperCase()}-${day.slice(2).replaceAll("-", "")}-${signature(id, day)}`;
}

/** Splits and normalises a typed code; null if it cannot be one of ours. */
export function parseCertificateCode(input: string) {
  const clean = input.toUpperCase().replace(/[^0-9A-Z]/g, "");
  const m = clean.match(/^([0-9A-F]{8})(\d{6})([A-Z2-9]{8})$/);
  if (!m) return null;
  const day = `20${m[2].slice(0, 2)}-${m[2].slice(2, 4)}-${m[2].slice(4, 6)}`;
  if (Number.isNaN(Date.parse(day + "T00:00:00Z"))) return null;
  return { prefix: m[1].toLowerCase(), day, sig: m[3] };
}

export function checkSignature(id: string, day: string, sig: string) {
  const a = Buffer.from(signature(id, day));
  const b = Buffer.from(sig);
  return a.length === b.length && timingSafeEqual(a, b);
}

export function verifyUrl(code?: string) {
  const base = (
    process.env.APP_URL || "https://member.ssvpotsdamerstr.de"
  ).replace(/\/+$/, "");
  return base + "/pruefen" + (code ? "?code=" + code : "");
}

// ---------------------------------------------------------------------------------------------
// E-mail text (German first, then English)

export function certificateMessage(firstName: string, club: string) {
  return {
    subject: `Deine Mitgliedsbescheinigung / Your membership certificate – ${club}`,
    text: [
      `Hallo ${firstName},`,
      "",
      `im Anhang findest du deine Mitgliedsbescheinigung der ${club} als PDF.`,
      "Das Dokument wurde maschinell erstellt und ist auch ohne Unterschrift gültig. Über den Prüfcode im Dokument lässt sich die Echtheit jederzeit online bestätigen.",
      "",
      "Falls du Fragen hast, antworte einfach auf diese E-Mail.",
      "",
      "Viele Grüße",
      club,
      "",
      "— English —",
      "",
      `Hello ${firstName},`,
      "",
      `please find attached your membership certificate from ${club} as a PDF.`,
      "The document was generated electronically and is valid without a signature. Its authenticity can be confirmed online at any time using the verification code on the document.",
      "",
      "If you have any questions, simply reply to this email.",
      "",
      "Kind regards",
      club,
    ].join("\n"),
  };
}

export function certificateFileName(
  firstName: string,
  lastName: string,
  variant: CertVariant,
) {
  const ascii =
    `${firstName} ${lastName}`
      .replace(
        /[äöüÄÖÜß]/g,
        (c) =>
          ({ ä: "ae", ö: "oe", ü: "ue", Ä: "Ae", Ö: "Oe", Ü: "Ue", ß: "ss" })[
            c
          ]!,
      )
      .normalize("NFKD")
      .replace(/\p{M}/gu, "")
      .replace(/[^A-Za-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 60) || "Mitglied";
  return `Mitgliedsbescheinigung-${ascii}${variant === "print" ? "-Druck" : ""}.pdf`;
}

// ---------------------------------------------------------------------------------------------
// PDF

type Run = { text: string; bold?: boolean };

const A4: [number, number] = [595.28, 841.89];
const LEFT = 62;
const RIGHT = 533;
const WIDTH = RIGHT - LEFT;
const INK = rgb(0.1, 0.13, 0.16);
const GREY = rgb(0.4, 0.45, 0.48);
const RULE = rgb(0.82, 0.85, 0.86);
const GREEN = rgb(0.07, 0.38, 0.28);
const TINT = rgb(0.93, 0.97, 0.95);

export async function certificatePdf(
  row: CertMember,
  texts: CertTexts,
  variant: CertVariant,
  issued: Date = new Date(),
) {
  if (!certificateAvailable(row)) throw new Error("Certificate unavailable");
  const club = texts.clubName.trim() || "Verein";
  const name = `${row.first_name} ${row.last_name}`;
  const day = berlinDay(issued);
  const code = certificateCode(row.id, day);
  const place = texts.certPlace.trim();
  const sinceDe = memberSince(row, "de");
  const sinceEn = memberSince(row, "en");

  const doc = await PDFDocument.create();
  doc.registerFontkit(fontkit);
  const regular = await doc.embedFont(await pdfFont(), { subset: true });
  // pdf-lib's subsetter drops glyphs of this cut, so it is embedded whole (~600 KB).
  const bold = await doc.embedFont(await pdfFontBold(), { subset: false });

  const everything = club + name + CERT_TEXT_KEYS.map((k) => texts[k]).join("");
  const sets = [
    new Set(regular.getCharacterSet()),
    new Set(bold.getCharacterSet()),
  ];
  const unsupported = [
    ...new Set(
      [...everything].filter(
        (c) => c !== "\n" && sets.some((s) => !s.has(c.codePointAt(0)!)),
      ),
    ),
  ];
  if (unsupported.length) throw new PdfGlyphError(unsupported);

  const page = doc.addPage(A4);
  const W = A4[0];

  const center = (
    text: string,
    y: number,
    font: PDFFont,
    size: number,
    color: RGB = INK,
  ) => {
    const w = font.widthOfTextAtSize(text, size);
    page.drawText(text, { x: (W - w) / 2, y, font, size, color });
  };
  const rightText = (
    text: string,
    y: number,
    font: PDFFont,
    size: number,
    color: RGB = INK,
  ) =>
    page.drawText(text, {
      x: RIGHT - font.widthOfTextAtSize(text, size),
      y,
      font,
      size,
      color,
    });

  // Letterhead
  page.drawRectangle({ x: 0, y: A4[1] - 8, width: W, height: 8, color: GREEN });
  let y = 776;
  center(club, y, bold, 17);
  y -= 18;
  if (texts.certSubtitle.trim()) {
    center(texts.certSubtitle.trim(), y, regular, 9.5, GREY);
    y -= 14;
  }
  if (texts.certAddress.trim()) {
    center(texts.certAddress.trim(), y, regular, 8.5, GREY);
    y -= 14;
  }
  y -= 6;
  page.drawLine({
    start: { x: LEFT, y },
    end: { x: RIGHT, y },
    thickness: 0.8,
    color: RULE,
  });

  // Place and date
  y -= 30;
  rightText(
    `${place ? place + ", " : ""}${longDate(day, "de")}`,
    y,
    regular,
    10,
  );

  // Title
  y -= 50;
  center("Mitgliedsbescheinigung", y, bold, 22);
  y -= 20;
  center("Certificate of Membership", y, regular, 12, GREY);

  // German text
  y -= 44;
  const de: Run[] = [
    { text: "Hiermit bestätigen wir, dass " },
    { text: name, bold: true },
    { text: ", geboren am " },
    { text: shortDate(row.birth_date), bold: true },
    { text: `, Mitglied der ${club} ist.` },
  ];
  if (sinceDe)
    de.push(
      { text: " Die Mitgliedschaft besteht seit " },
      { text: sinceDe, bold: true },
      { text: "." },
    );
  de.push({
    text: " Diese Bescheinigung wird auf Wunsch des Mitglieds zur Vorlage bei Dritten ausgestellt.",
  });
  y = paragraph(page, de, y, { regular, bold, size: 11, gap: 17, color: INK });

  // English text
  y -= 16;
  page.drawText("ENGLISH", { x: LEFT, y, font: bold, size: 7.5, color: GREEN });
  y -= 15;
  const en: Run[] = [
    { text: "We hereby confirm that " },
    { text: name, bold: true },
    { text: ", born on " },
    { text: longDate(row.birth_date, "en"), bold: true },
    { text: `, is a member of ${club}${club.endsWith(".") ? "" : "."}` },
  ];
  if (sinceEn)
    en.push(
      { text: " The membership has existed since " },
      { text: sinceEn, bold: true },
      { text: "." },
    );
  en.push({
    text: " This certificate is issued at the request of the member for presentation to third parties.",
  });
  y = paragraph(page, en, y, { regular, bold, size: 10, gap: 15, color: GREY });

  // Details
  y -= 26;
  const details: [string, string][] = [
    ["Vorgangsnummer / Reference no.", row.id],
    ["Ausstellungsdatum / Date of issue", `${shortDate(day)}`],
  ];
  if (variant === "digital")
    details.push(["Prüfcode / Verification code", code]);
  for (const [label, value] of details) {
    page.drawText(label, { x: LEFT, y, font: regular, size: 8.5, color: GREY });
    page.drawText(value, {
      x: LEFT + 170,
      y,
      font: label.startsWith("Prüf") ? bold : regular,
      size: 9,
      color: INK,
    });
    y -= 15;
  }

  y -= 26;
  if (variant === "digital") {
    // Machine-generated notice instead of a signature.
    const lines: { runs: Run[]; size: number; color: RGB }[] = [
      {
        runs: [
          {
            text: "Maschinell erstellt – gültig ohne Unterschrift",
            bold: true,
          },
        ],
        size: 10.5,
        color: GREEN,
      },
      {
        runs: [
          {
            text: `Dieses Dokument wurde elektronisch über das Mitgliederportal der ${club} erstellt und ist ohne Unterschrift gültig. Die Echtheit kann mit dem Prüfcode unter ${verifyUrl()} bestätigt werden.`,
          },
        ],
        size: 9,
        color: INK,
      },
      {
        runs: [
          {
            text: "Generated electronically – valid without signature",
            bold: true,
          },
        ],
        size: 9.5,
        color: GREEN,
      },
      {
        runs: [
          {
            text: `This document was generated electronically by the membership portal of ${club} and is valid without a signature. Its authenticity can be confirmed with the verification code at ${verifyUrl()}.`,
          },
        ],
        size: 8.5,
        color: GREY,
      },
    ];
    // Measure first so the tinted box fits the text.
    const pad = 14;
    const inner = WIDTH - 2 * pad - 4;
    const heights = lines.map(
      (l) =>
        layout(l.runs, { regular, bold, size: l.size }, inner).length *
        (l.size + 4.5),
    );
    const height = heights.reduce((a, b) => a + b, 0) + 2 * pad + 8;
    page.drawRectangle({
      x: LEFT,
      y: y - height + 10,
      width: WIDTH,
      height,
      color: TINT,
    });
    page.drawRectangle({
      x: LEFT,
      y: y - height + 10,
      width: 3,
      height,
      color: GREEN,
    });
    let by = y - pad + 2;
    lines.forEach((l, i) => {
      if (i === 2) by -= 8;
      by = paragraph(page, l.runs, by, {
        regular,
        bold,
        size: l.size,
        gap: l.size + 4.5,
        color: l.color,
        boldColor: l.color,
        x: LEFT + pad + 4,
        width: inner,
      });
    });
    y -= height + 10;
  } else {
    // Hand signature: name and position intentionally left blank.
    page.drawText("Mit freundlichen Grüßen / Kind regards", {
      x: LEFT,
      y,
      font: regular,
      size: 10,
      color: INK,
    });
    y -= 62;
    const colW = 260;
    const line = (x: number, yy: number, w: number) =>
      page.drawLine({
        start: { x, y: yy },
        end: { x: x + w, y: yy },
        thickness: 0.7,
        color: INK,
      });
    line(LEFT, y, colW);
    page.drawText("Unterschrift / Signature", {
      x: LEFT,
      y: y - 12,
      font: regular,
      size: 8,
      color: GREY,
    });
    y -= 44;
    line(LEFT, y, colW);
    page.drawText(
      "Name und Funktion in Druckbuchstaben / Name and position (block letters)",
      {
        x: LEFT,
        y: y - 12,
        font: regular,
        size: 8,
        color: GREY,
      },
    );
    y -= 44;
    line(LEFT, y, colW);
    page.drawText("Ort, Datum / Place, date", {
      x: LEFT,
      y: y - 12,
      font: regular,
      size: 8,
      color: GREY,
    });
    if (place)
      page.drawText(`${place}, ${shortDate(day)}`, {
        x: LEFT + 2,
        y: y + 5,
        font: regular,
        size: 10,
        color: INK,
      });

    y -= 30;
  }

  // Footer
  if (texts.contactEmail.trim())
    page.drawText(`Für Rückfragen / Enquiries: ${texts.contactEmail.trim()}`, {
      x: LEFT,
      y: 92,
      font: regular,
      size: 8.5,
      color: GREY,
    });
  page.drawLine({
    start: { x: LEFT, y: 72 },
    end: { x: RIGHT, y: 72 },
    thickness: 0.6,
    color: RULE,
  });
  const foot = [club, texts.certSubtitle.trim()].filter(Boolean).join(" · ");
  center(foot, 56, regular, 7.5, GREY);
  if (variant === "digital")
    center(`Prüfcode / Verification code: ${code}`, 44, regular, 7.5, GREY);

  doc.setTitle("Mitgliedsbescheinigung / Certificate of Membership");
  doc.setAuthor(club);
  doc.setSubject(name);
  doc.setCreator("Mitgliederportal");
  doc.setCreationDate(issued);
  return doc.save();
}

type Fonts = { regular: PDFFont; bold: PDFFont; size: number };

/** Word-wraps runs of regular and bold text; returns lines of [text, bold] pieces. */
function layout(runs: Run[], { regular, bold, size }: Fonts, width: number) {
  const words: { text: string; bold: boolean; space: boolean }[] = [];
  for (const run of runs) {
    run.text.split(/(\s+)/).forEach((part) => {
      if (!part) return;
      if (/^\s+$/.test(part)) {
        if (words.length) words[words.length - 1].space = true;
      } else words.push({ text: part, bold: !!run.bold, space: false });
    });
  }
  const w = (t: string, b: boolean) =>
    (b ? bold : regular).widthOfTextAtSize(t, size);
  const spaceW = regular.widthOfTextAtSize(" ", size);
  const lines: { text: string; bold: boolean; space: boolean }[][] = [[]];
  let x = 0;
  for (const word of words) {
    const line = lines[lines.length - 1];
    const prev = line[line.length - 1];
    const gap = prev?.space ? spaceW : 0;
    if (line.length && x + gap + w(word.text, word.bold) > width) {
      lines.push([word]);
      x = w(word.text, word.bold);
    } else {
      line.push(word);
      x += gap + w(word.text, word.bold);
    }
  }
  return lines;
}

function paragraph(
  page: PDFPage,
  runs: Run[],
  y: number,
  opts: Fonts & {
    gap: number;
    color: RGB;
    boldColor?: RGB;
    x?: number;
    width?: number;
  },
) {
  const x0 = opts.x ?? LEFT;
  const spaceW = opts.regular.widthOfTextAtSize(" ", opts.size);
  for (const line of layout(runs, opts, opts.width ?? WIDTH)) {
    let x = x0;
    line.forEach((word, i) => {
      const font = word.bold ? opts.bold : opts.regular;
      page.drawText(word.text, {
        x,
        y,
        font,
        size: opts.size,
        color: word.bold ? (opts.boldColor ?? INK) : opts.color,
      });
      x +=
        font.widthOfTextAtSize(word.text, opts.size) +
        (word.space && i < line.length - 1 ? spaceW : 0);
    });
    y -= opts.gap;
  }
  return y;
}
